### ISSUE TITLE
ModuleNotFoundError: No module named 'Area'

### ISSUE THREAD

**Issue by sumit1212** [deepakrana47/segmentation-of-wheat-connected-in-a-picture#1]
**When Run File This error occur **
` python segment_formation_test.py 
Traceback (most recent call last):
  File "segment_formation_test.py", line 3, in <module>
    from L2_Segmentation_v3 import segment_image4
  File "/home/skymet/Documents/segmentation-of-wheat-connected-in-a-picture-master/L2_Segmentation_v3.py", line 2, in <module>
    from Area import areaThreshold_by_havg, areaThreshold_by_avg
ModuleNotFoundError: No module named 'Area'
`
Thank You for quick response.

**Comment by deepakrana47** [comment]
I had resoled the error check if work.

**Comment by sumit1212** [comment]
**Thank you for help**

> Run - python segment_formation_test.py 
> this output will give and my input image is also attached.
> so how to calculate no of grain in image

```
overlapping_grain/m-IMG_20161016_124756_1966.jpg
{5.0: [0, 103, 0, 134], 6.0: [0, 19, 74, 115]}
[  779 13802] 2
```
![m-IMG_20161016_124756_1966](https://user-images.githubusercontent.com/28036324/66508661-2cba4900-eaef-11e9-8375-c0d5467b4ff7.jpg)

**Comment by deepakrana47** [comment]
```
overlapping_grain/m-IMG_20161016_124756_1966.jpg
{5.0: [0, 103, 0, 134], 6.0: [0, 19, 74, 115]}
[  779 13802] 2
```
The line 3 shows the number of grains detected in the given picture (line 1) and 

> so how to calculate no of grain in image

For calculating the number of grain you have to come up with the method that works for you (as the method described in this project may or may not work for you).

**Comment by sumit1212** [comment]
It means that will show wrong count from image but when put the output folder contain right result i.e. fetch single grain from image (3 image contain).
How localise and mask the object in image.

Thank you for that I thing this will help me and solve my problem.
I thing number of data same as your data set for localising and masking then it will work.
not say completely work for me but it help me find 60 % accuracy and count no. of paddy in image.

Last question - How to masking the object in image and background black.

**Comment by sumit1212** [comment]
how to preparing image for training and masking those images. 
**masking the object in image and background black.**

**Thanks**

**Comment by deepakrana47** [comment]
If you had gone through the code (L2_Segmentation.py) you will see the following lines:

> 40    ########################## 1st level of segmentation #############################
 ...
63    # print " Level 1 segmentation Finished"
64    ####################### 1st level of segmentation Finished ########################

this is the first level of segmentation where the masking of object in image and background removel takeing place.

**Comment by sumit1212** [comment]
It's really help me a lot.
Thank you very much for that  @deepakrana47

![2](https://user-images.githubusercontent.com/28036324/67144712-7517fa80-f297-11e9-890b-c1b6ba1a830c.jpg)

![img](https://user-images.githubusercontent.com/28036324/67144693-18b4db00-f297-11e9-8320-561843f9ce63.png)

I'm asking - It is create classifier for paddy images to identify paddy from image.
sorry to ask you but I have not much idea about images, so please which way to do to find result.
